##### General #####
set -g renumber-windows on

set -g monitor-activity off
set -g monitor-bell on
set -g bell-action any

##### Status line #####
set -g status-style "bg=colour236,fg=yellow,dim"
set -g window-status-current-style "fg=brightcyan,bg=colour236"
set -g window-status-style "fg=brightred,bg=colour236,bright"
set -g window-status-separator "#[fg=white,bg=colour236]|#[default]"
set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}\"#{=41:pane_title}\" %H:%M %d-%b-%y"
set -g status-right-length 60

##### Prefix #####
set -g prefix C-s
unbind C-b
bind C-s send-prefix

##### Copy mode / Word behavior #####
set -g mode-keys vi
# set select-word separator
set -g word-separators ' -@.,:;()[]{}<>/\\|+="'
set -ag word-separators "'"

##### Copy word keybinds #####
# Prefix + C-c, copy word under cursor to tmux and system clipboard
bind-key C-c run-shell ' \
  p="#{pane_id}"; \
  tmux copy-mode -t "$p"; \
  tmux send-keys -t "$p" -X select-word; \
  tmux send-keys -t "$p" -X copy-selection-and-cancel \
'

##### Plugin List #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Put this at the last line
run '~/.tmux/plugins/tpm/tpm'
